version: '3'
services:
  dev:
    image: thierrysans/pintos
    container_name: pintos_cocopam
    volumes:
      - .:/pintos
    working_dir: /pintos
    hostname: pintos_cocopam
    tty: true
    entrypoint: bash
